/**
 * Tests for SMS message content generated by lib/sms.ts helper functions.
 *
 * GAP: notifyAdminSMS, sendFollowUpSMS, sendDepositConfirmationSMS, sendReferralSMS
 * are completely untested. The message templates contain business-critical info
 * (Luca's phone, URLs, client first names) that can regress silently.
 *
 * These tests reproduce the message-building logic inline (no network/DB)
 * to lock down the template contract.
 *
 * Run: node --test tests/sms-messages.test.mjs
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';

const LUCA_PHONE = '581-307-5983';
const BASE_URL = 'https://novus-epoxy.vercel.app';

// ── Inlined message builders from lib/sms.ts ─────────────────────────────────

function buildAdminMsg(quoteId, clientName) {
  return `Novus Epoxy: Nouveau devis #${quoteId} de ${clientName} a approuver. ${BASE_URL}/dashboard/devis/${quoteId}`;
}

function buildFollowUpMsg(clientName, quoteId) {
  const prenom = clientName.split(' ')[0];
  return `Salut ${prenom}! C'est Luca de Novus Epoxy. Je voulais m'assurer que t'avais bien recu notre soumission #${quoteId}. Si t'as des questions ou tu veux qu'on en discute, n'hesite pas a m'appeler au ${LUCA_PHONE}. Bonne journee!`;
}

function buildDepositConfirmationMsg(clientName, jour1Date, jour2Date) {
  const prenom = clientName.split(' ')[0];
  const datesInfo = jour1Date && jour2Date
    ? ` Tes dates du ${jour1Date} et ${jour2Date} sont confirmees.`
    : '';
  return `${prenom}, c'est Luca de Novus Epoxy! Depot bien recu, merci!${datesInfo} On a hate de transformer ton plancher! Questions? ${LUCA_PHONE}`;
}

function buildReferralMsg(clientName) {
  const prenom = clientName.split(' ')[0];
  return `Salut ${prenom}! C'est Luca de Novus Epoxy. Ca fait deja quelques mois qu'on a fait ton plancher — j'espere que t'en profites! Si tu connais quelqu'un qui voudrait la meme chose, on offre 100$ de rabais pour chaque reference. Passe le mot! ${LUCA_PHONE}`;
}

// ── notifyAdminSMS message ────────────────────────────────────────────────────

test('admin SMS: includes quote ID', () => {
  const msg = buildAdminMsg(42, 'Bernard Gagné');
  assert.ok(msg.includes('#42'), 'should include #42');
});

test('admin SMS: includes client name', () => {
  const msg = buildAdminMsg(42, 'Bernard Gagné');
  assert.ok(msg.includes('Bernard Gagné'));
});

test('admin SMS: includes dashboard URL for that quote', () => {
  const msg = buildAdminMsg(42, 'Bernard Gagné');
  assert.ok(msg.includes(`${BASE_URL}/dashboard/devis/42`));
});

test('admin SMS: mentions Novus Epoxy', () => {
  const msg = buildAdminMsg(1, 'Test');
  assert.ok(msg.includes('Novus Epoxy'));
});

// ── sendFollowUpSMS message ───────────────────────────────────────────────────

test('followup SMS: uses first name only', () => {
  const msg = buildFollowUpMsg('Bernard Gagné', 10);
  assert.ok(msg.startsWith('Salut Bernard!'));
  assert.ok(!msg.includes('Gagné'));
});

test('followup SMS: includes quote number', () => {
  const msg = buildFollowUpMsg('Marie Tremblay', 99);
  assert.ok(msg.includes('#99'));
});

test('followup SMS: includes Luca phone', () => {
  const msg = buildFollowUpMsg('Jean', 5);
  assert.ok(msg.includes(LUCA_PHONE));
});

test('followup SMS: single-word name handled correctly', () => {
  const msg = buildFollowUpMsg('Pierre', 7);
  assert.ok(msg.startsWith('Salut Pierre!'));
});

// ── sendDepositConfirmationSMS message ────────────────────────────────────────

test('deposit SMS: includes first name only', () => {
  const msg = buildDepositConfirmationMsg('Julie Côté', '10 juin', '11 juin');
  assert.ok(msg.startsWith('Julie,'));
  assert.ok(!msg.includes('Côté'));
});

test('deposit SMS: with dates → confirms both dates', () => {
  const msg = buildDepositConfirmationMsg('Jean', '10 juin', '11 juin');
  assert.ok(msg.includes('10 juin'));
  assert.ok(msg.includes('11 juin'));
});

test('deposit SMS: without dates → no date string', () => {
  const msg = buildDepositConfirmationMsg('Jean', undefined, undefined);
  assert.ok(!msg.includes('confirmees'));
});

test('deposit SMS: without jour2 only → no date string', () => {
  const msg = buildDepositConfirmationMsg('Jean', '10 juin', undefined);
  assert.ok(!msg.includes('10 juin'), 'partial dates should not appear');
});

test('deposit SMS: includes Luca phone', () => {
  const msg = buildDepositConfirmationMsg('Alex', '1 juillet', '2 juillet');
  assert.ok(msg.includes(LUCA_PHONE));
});

test('deposit SMS: mentions depot bien recu', () => {
  const msg = buildDepositConfirmationMsg('Alex', undefined, undefined);
  assert.ok(msg.includes('Depot bien recu'));
});

// ── sendReferralSMS message ───────────────────────────────────────────────────

test('referral SMS: uses first name only', () => {
  const msg = buildReferralMsg('Bernard Gagné');
  assert.ok(msg.startsWith('Salut Bernard!'));
  assert.ok(!msg.includes('Gagné'));
});

test('referral SMS: mentions 100$ rabais', () => {
  const msg = buildReferralMsg('Marc');
  assert.ok(msg.includes('100$'));
});

test('referral SMS: includes Luca phone', () => {
  const msg = buildReferralMsg('Marc');
  assert.ok(msg.includes(LUCA_PHONE));
});

test('referral SMS: mentions reference', () => {
  const msg = buildReferralMsg('Marc');
  assert.ok(msg.includes('reference'));
});
